//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationWPF.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyFurniture
    {
        public int Id { get; set; }
        public int IdSales { get; set; }
        public int IdFurniture { get; set; }
        public int Count { get; set; }
        public decimal DeliveryCost { get; set; }
        public int Discount { get; set; }
    
        public virtual Furniture Furniture { get; set; }
        public virtual Sales Sales { get; set; }
    }
}
