//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationWPF.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Furniture()
        {
            this.BuyFurniture = new HashSet<BuyFurniture>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdType { get; set; }
        public int IdSupplier { get; set; }
        public int IdProducer { get; set; }
        public decimal Cost { get; set; }
        public decimal InstallationPrice { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public int Existance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyFurniture> BuyFurniture { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Type Type { get; set; }
    }
}
